// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tvydgiokjqwkymgdcuzf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR2eWRnaW9ranF3a3ltZ2RjdXpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NTIzODUsImV4cCI6MjA3MzQyODM4NX0.0dWZ1V3DgQuq4_veyis7-6TBwCP-JTa2VLZKEW-Gdwo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});